AllCops:
  Exclude:
    - 'bin/**/*'
    - 'lib/**/*'
    - 'pkg/**/*'
    - 'sig/**/*'
    - 'vendor/**/*'
    - '*gemspec'
    
#https://docs.rubocop.org/rubocop/cops_style.html
#https://gist.github.com/linyows/ace586b118f87291ed3e

Layout/LineLength:
  Max: 120
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
