name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        bundler-cache: true

    - name: Security audit dependencies
      run: bin/bundler-audit --update
    - name: Security audit application code
      run: bin/brakeman -q -w2
    - name: Lint Ruby files
      run: bin/rubocop --parallel

    - name: Gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

#Setting->Actions->General->Workflow permissions->"Read and write permissions"
    - name: Git push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -f *.gem
        git commit -m 'pushing new gem'
        git push
