name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: Run tests
      run: bundle exec rake
    - name: Security audit dependencies
      run: bin/bundler-audit --update
    - name: Security audit application code
      run: bin/brakeman -q -w2
    - name: Lint Ruby files
      run: bin/rubocop --parallel

    - name: Gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

#Setting->Actions->General->Workflow permissions->"Read and write permissions"
    - name: Git push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -f *.gem
        git commit -m 'pushing new gem'
        git push
